# Generated by Django 4.1.2 on 2022-10-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon raqam')),
                ('code', models.CharField(max_length=10, verbose_name='Kod')),
            ],
            options={
                'verbose_name': 'Telefon raqamni tasdiqlash',
                'verbose_name_plural': 'Telefon raqam tasdiqlash',
            },
        ),
    ]
