# Generated by Django 4.1.3 on 2022-11-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_verifyphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyphone',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='verifyphone',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
    ]
